[package]
edition = "2021"
name = "todolist"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.99"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
